feature/CCT-257
cloudwalk/mruby-pax pull request #12
Opened 2020-11-17 13:40 UTC by spinardi

This PR holds the core updates related to [CCT-257](https://cloudwalk.atlassian.net/browse/CCT-257) and an additional full review of system utilities at the mrbgem mruby-pax:

- **This PR is related to another 2 PRs (`da_funk` and `main`)** (I'll will update this one with links as soon as I have them)
- C code changes are working fine and have a _small-but-**important**_ **protection** against stressing both file system and battery itself.
   - Said protection (see above) could not be coded in Ruby because _mruby 1.x_ seems to not support class variables `@@` and mutexes (at least, not natively)

C code changes mainly contemplates:
- Code formatting
   - Tab: 4 spaces _(only C code, for Ruby: 2 spaces)_
- Code documentation
   - Doxygen's `@brief` tag as function headers
- Battery capacity API review
   - `mrb_s_battery()` new implementation (protected against thread concurrency)
   - `mrb_system_init()` update, to be compliant with the new implementation of `mrb_s_battery()` (see above)

Ruby code changes mainly contemplates:
- Code documentation
   - _loosely based on YARD and RuboCop_
- APIs implementation review 
   - `backlight` method review for dynamic capabilities (previously static)
   - `battery_capacity_type` method creation

2020-11-20 20:29 UTC, scalone requested changes
@spinardi can you follow the library whitespace indentation pattern. We can discuss the indentation in other PR, what you think?

2020-11-20 20:29 UTC, scalone commented on src/system.c
> -  mrb_define_class_method(mrb , system , "reload"          , mrb_system_s_reload       , MRB_ARGS_NONE());
I would say that was easier to read.

2020-11-20 20:29 UTC, scalone commented on src/system.c
> +    t.Second = second;
I would say that was easier to read

2020-11-23 13:10 UTC, spinardi commented
Thanks for reviewing, @scalone! I have updated the PR, reverting some indentation and formatting changes to keep Ruby and C/C++ code more alike.

2020-11-23 13:50 UTC, william-rgt approved these changes

2020-11-23 13:51 UTC, merged